import sqlite3

baza = "Premier_Leauge.db"

ARS={'KOSCIELNY': ['DEF', 'ARS', 6.0], 'CECH': ['GK', 'ARS', 5.5], 'COQUELIN': ['MID', 'ARS', 4.5], 'WALCOTT': ['MID', 'ARS', 7.5], 'BELLERIN': ['DEF', 'ARS', 6.0], 'JENKINSON': ['DEF', 'ARS', 4.5], 'RAMSEY': ['MID', 'ARS', 7.0], 'OSPINA': ['GK', 'ARS', 5.0], 'GABRIEL': ['DEF', 'ARS', 5.0], 'XHAKA': ['MID', 'ARS', 5.5], 'CHAMBERLAIN': ['MID', 'ARS', 6.0], 'GIROUD': ['FWD', 'ARS', 8.5], 'MARTINEZ': ['GK', 'ARS', 4.0], 'WELBECK': ['FWD', 'ARS', 7.5], 'MERTESACKER': ['DEF', 'ARS', 5.0], 'IWOBI': ['MID', 'ARS', 5.5], 'KOLASINAC': ['DEF', 'ARS', 6.0], 'OZIL': ['MID', 'ARS', 9.5], 'MUSTAFI': ['DEF', 'ARS', 5.5], 'GIBBS': ['DEF', 'ARS', 5.0], 'HOLDING': ['DEF', 'ARS', 5.0], 'WILSHERE': ['MID', 'ARS', 5.5], 'ELNENY': ['MID', 'ARS', 4.5], 'LACAZETTE': ['FWD', 'ARS', 10.5], 'CAZORLA': ['MID', 'ARS', 7.0], 'MONREAL': ['DEF', 'ARS', 5.5], 'SANCHEZ': ['MID', 'ARS', 12.0], 'PEREZ': ['FWD', 'ARS', 7.5]}
BOU={'PUGH': ['MID', 'BOU', 5.0], 'MINGS': ['DEF', 'BOU', 4.5], 'CALLUM WILSON': ['FWD', 'BOU', 6.0], 'MOUSSET': ['FWD', 'BOU', 5.0], 'BEGOVIC': ['GK', 'BOU', 4.5], 'GRADEL': ['MID', 'BOU', 5.0], 'KING': ['FWD', 'BOU', 7.5], 'DEFOE': ['FWD', 'BOU', 8.0], 'STEVE COOK': ['DEF', 'BOU', 5.0], 'LEWIS COOK': ['MID', 'BOU', 4.5], 'AFOBE': ['FWD', 'BOU', 6.0], 'BRAD SMITH': ['DEF', 'BOU', 4.0], 'FRASER': ['MID', 'BOU', 5.5], 'BORUC': ['GK', 'BOU', 4.5], 'ARTER': ['MID', 'BOU', 5.0], 'IBE': ['MID', 'BOU', 5.0], 'DANIELS': ['DEF', 'BOU', 5.0], 'AKE': ['DEF', 'BOU', 5.0], 'FRANCIS': ['DEF', 'BOU', 4.5], 'ADAM SMITH': ['DEF', 'BOU', 5.0], 'STANISLAS': ['MID', 'BOU', 6.0], 'SURMAN': ['MID', 'BOU', 4.5], 'GOSLING': ['MID', 'BOU', 5.0], 'FEDERICI': ['GK', 'BOU', 4.0]}
BHA={'MARCH': ['MID', 'BHA', 5.0], 'HEMED': ['FWD', 'BHA', 5.0], 'SKALAK': ['MID', 'BHA', 5.0], 'SIDWELL': ['MID', 'BHA', 4.5], 'DALE STEPHENS': ['MID', 'BHA', 4.5], 'BONG': ['DEF', 'BHA', 4.5], 'MURRAY': ['FWD', 'BHA', 6.0], 'GOLDSON': ['DEF', 'BHA', 4.0], 'HUNEMEIER': ['DEF', 'BHA', 4.0], 'ROSENIOR': ['DEF', 'BHA', 4.0], 'MAENPAA': ['GK', 'BHA', 4.0], 'BRUNO': ['DEF', 'BHA', 4.5], 'KAYAL': ['MID', 'BHA', 4.5], 'NORWOOD': ['MID', 'BHA', 4.5], 'DUNK': ['DEF', 'BHA', 4.5], 'RYAN': ['GK', 'BHA', 4.5], 'JAMIE MURPHY': ['MID', 'BHA', 5.0], 'DUFFY': ['DEF', 'BHA', 4.5], 'GROSS': ['MID', 'BHA', 5.5], 'BALDOCK': ['FWD', 'BHA', 5.0], 'KNOCKAERT': ['MID', 'BHA', 6.0]}
BUR={'GUDMUNDSSON': ['MID', 'BUR', 5.0], 'DEFOUR': ['MID', 'BUR', 5.5], 'WARD': ['DEF', 'BUR', 4.5], 'VOKES': ['FWD', 'BUR', 6.0], 'HENDRICK': ['MID', 'BUR', 5.5], 'WESTWOOD': ['MID', 'BUR', 4.5], 'ANDRE GRAY': ['FWD', 'BUR', 6.5], 'HEATON': ['GK', 'BUR', 5.0], 'WALTERS': ['MID', 'BUR', 5.5], 'MEE': ['DEF', 'BUR', 4.5], 'KEVIN LONG': ['DEF', 'BUR', 4.0], 'CORK': ['MID', 'BUR', 4.5], 'TARKOWSKI': ['DEF', 'BUR', 4.5], 'LOWTON': ['DEF', 'BUR', 4.5], 'BARNES': ['FWD', 'BUR', 5.5], 'TAYLOR': ['DEF', 'BUR', 4.5], 'ROBINSON': ['GK', 'BUR', 4.5], 'BRADY': ['MID', 'BUR', 5.5], 'MARNEY': ['MID', 'BUR', 4.5], 'ARFIELD': ['MID', 'BUR', 5.0]}
CHE={'BATSHUAYI': ['FWD', 'CHE', 8.5], 'WILLIAN': ['MID', 'CHE', 7.0], 'ZOUMA': ['DEF', 'CHE', 5.5], 'HAZARD': ['MID', 'CHE', 10.5], 'EDUARDO': ['GK', 'CHE', 5.0], 'DAVID LUIZ': ['DEF', 'CHE', 6.0], 'CABALLERO': ['GK', 'CHE', 5.0], 'CAHILL': ['DEF', 'CHE', 6.5], 'KENEDY': ['MID', 'CHE', 5.0], 'PEDRO': ['MID', 'CHE', 8.0], 'KANTE': ['MID', 'CHE', 5.0], 'COSTA': ['FWD', 'CHE', 10.0], 'COURTOIS': ['GK', 'CHE', 5.5], 'ALONSO': ['DEF', 'CHE', 7.0], 'FABREGAS': ['MID', 'CHE', 7.0], 'AZPILICUETA': ['DEF', 'CHE', 6.5], 'RUDIGER': ['DEF', 'CHE', 6.0], 'CHALOBAH': ['MID', 'CHE', 4.5], 'MATIC': ['MID', 'CHE', 5.0], 'MOSES': ['DEF', 'CHE', 6.5]}
CRY={'LOFTUS-CHEEK': ['MID', 'CRY', 4.5],'BENTEKE': ['FWD', 'CRY', 8.0], 'WICKHAM': ['FWD', 'CRY', 5.5], 'KELLY': ['DEF', 'CRY', 4.5], 'DELANEY': ['DEF', 'CRY', 4.5], 'HENNESSEY': ['GK', 'CRY', 4.5], 'CABAYE': ['MID', 'CRY', 5.5], 'DANN': ['DEF', 'CRY', 5.0], 'ZAHA': ['MID', 'CRY', 7.0], 'TOWNSEND': ['MID', 'CRY', 6.0], 'MILIVOJEVIC': ['MID', 'CRY', 5.0], 'PUNCHEON': ['MID', 'CRY', 5.0], 'SPERONI': ['GK', 'CRY', 4.0], 'SCHLUPP': ['DEF', 'CRY', 5.0], 'JOEL WARD': ['DEF', 'CRY', 5.0], 'SAKO': ['MID', 'CRY', 5.0], 'LEE CHUNG-YONG': ['MID', 'CRY', 4.5], 'TOMKINS': ['DEF', 'CRY', 4.5], 'VAN AANHOLT': ['DEF', 'CRY', 5.5], 'SOUARE': ['DEF', 'CRY', 4.5], 'MCARTHUR': ['MID', 'CRY', 4.5]}
EVE={'PICKFORD': ['GK', 'EVE', 5.0], 'FUNES MORI': ['DEF', 'EVE', 5.0], 'CALVERT-LEWIN': ['FWD', 'EVE', 5.0], 'HOLGATE': ['DEF', 'EVE', 4.5], 'LOOKMAN': ['MID', 'EVE', 5.5], 'SCHNEIDERLIN': ['MID', 'EVE', 5.0], 'DAVIES': ['MID', 'EVE', 5.5], 'WILLIAMS': ['DEF', 'EVE', 5.5], 'SANDRO': ['FWD', 'EVE', 7.5], 'LENNON': ['MID', 'EVE', 5.5], 'ROONEY': ['FWD', 'EVE', 7.5], 'BESIC': ['MID', 'EVE', 4.5], 'JAGIELKA': ['DEF', 'EVE', 5.0], 'PENNINGTON': ['DEF', 'EVE', 4.0], 'KLAASSEN': ['MID', 'EVE', 7.5], 'STEKELENBURG': ['GK', 'EVE', 4.5], 'GUEYE': ['MID', 'EVE', 5.0], 'COLEMAN': ['DEF', 'EVE', 6.5], 'BARRY': ['MID', 'EVE', 4.5], 'MCCARTHY': ['MID', 'EVE', 5.0], 'KENNY': ['DEF', 'EVE', 4.5], 'BARKLEY': ['MID', 'EVE', 7.5], 'MIRALLAS': ['MID', 'EVE', 6.5], 'BAINES': ['DEF', 'EVE', 6.0], 'BOLASIE': ['MID', 'EVE', 6.5], 'ROBLES': ['GK', 'EVE', 4.5], 'KEANE': ['DEF', 'EVE', 5.5]}
HUD={'BILLING': ['MID', 'HUD', 4.5], 'SCANNELL': ['MID', 'HUD', 4.5], 'STANKOVIC': ['DEF', 'HUD', 4.0], 'HEFELE': ['DEF', 'HUD', 4.5], 'MOOY': ['MID', 'HUD', 5.5], 'SMITH': ['DEF', 'HUD', 5.0], 'MOUNIE': ['FWD', 'HUD', 6.0], 'DANNY WILLIAMS': ['MID', 'HUD', 5.0], 'PAYNE': ['MID', 'HUD', 4.5], 'DEPOITRE': ['FWD', 'HUD', 5.5], 'VAN LA PARRA': ['MID', 'HUD', 5.0], 'JOEL COLEMAN': ['GK', 'HUD', 4.0], 'QUANER': ['FWD', 'HUD', 4.5], 'CRANIE': ['DEF', 'HUD', 4.0], 'KACHUNGA': ['MID', 'HUD', 6.0], 'SCHINDLER': ['DEF', 'HUD', 4.5], 'LOLLEY': ['MID', 'HUD', 4.5], 'ZANKA': ['DEF', 'HUD', 4.5], 'LOWE': ['DEF', 'HUD', 4.5], 'HUDSON': ['DEF', 'HUD', 4.0], 'PALMER': ['MID', 'HUD', 5.5], 'WHITEHEAD': ['MID', 'HUD', 4.5], 'INCE': ['MID', 'HUD', 6.0], 'BUNN': ['MID', 'HUD', 4.5], 'WELLS': ['FWD', 'HUD', 5.0], 'LOSSL': ['GK', 'HUD', 4.5], 'HOGG': ['MID', 'HUD', 4.5]}
LEI={'FUCHS': ['DEF', 'LEI', 5.0], 'SIMPSON': ['DEF', 'LEI', 4.5], 'GRAY': ['MID', 'LEI', 5.5], 'MORGAN': ['DEF', 'LEI', 4.5], 'VARDY': ['FWD', 'LEI', 8.5], 'NDIDI': ['MID', 'LEI', 5.0], 'BENALOUANE': ['DEF', 'LEI', 4.5], 'MAGUIRE': ['DEF', 'LEI', 5.0], 'HUTH': ['DEF', 'LEI', 5.0], 'OKAZAKI': ['FWD', 'LEI', 5.5], 'ULLOA': ['FWD', 'LEI', 5.0], 'CHILWELL': ['DEF', 'LEI', 4.5], 'AMARTEY': ['MID', 'LEI', 4.5], 'ALBRIGHTON': ['MID', 'LEI', 5.5], 'IBORRA': ['MID', 'LEI', 6.0], 'MENDY': ['MID', 'LEI', 4.5], 'DRINKWATER': ['MID', 'LEI', 5.0], 'HAMER': ['GK', 'LEI', 4.5], 'SLIMANI': ['FWD', 'LEI', 7.0], 'MUSA': ['MID', 'LEI', 6.5], 'SCHMEICHEL': ['GK', 'LEI', 5.0], 'MAHREZ': ['MID', 'LEI', 8.5], 'WAGUE': ['DEF', 'LEI', 4.5], 'ANDY KING': ['MID', 'LEI', 4.5]}
LIV={'SAKHO': ['DEF', 'LIV', 5.0], 'ALEXANDER-ARNOLD': ['DEF', 'LIV', 4.5], 'KLAVAN': ['DEF', 'LIV', 4.5], 'ORIGI': ['FWD', 'LIV', 7.5], 'LOVREN': ['DEF', 'LIV', 5.5], 'GOMEZ': ['DEF', 'LIV', 4.5], 'MATIP': ['DEF', 'LIV', 5.5], 'STURRIDGE': ['FWD', 'LIV', 8.0], 'MANE': ['MID', 'LIV', 9.5], 'WIJNALDUM': ['MID', 'LIV', 7.0], 'SHEYI OJO': ['MID', 'LIV', 5.0], 'MILNER': ['DEF', 'LIV', 6.5], 'HENDERSON': ['MID', 'LIV', 5.5], 'CLYNE': ['DEF', 'LIV', 5.5], 'COUTINHO': ['MID', 'LIV', 9.0], 'SALAH': ['MID', 'LIV', 9.0], 'CAN': ['MID', 'LIV', 5.0], 'GRUJIC': ['MID', 'LIV', 4.5], 'SOLANKE': ['FWD', 'LIV', 5.0], 'MORENO': ['DEF', 'LIV', 4.5], 'LUCAS': ['MID', 'LIV', 4.5], 'FIRMINO': ['FWD', 'LIV', 8.5], 'INGS': ['FWD', 'LIV', 5.5], 'KARIUS': ['GK', 'LIV', 5.0], 'LALLANA': ['MID', 'LIV', 7.5], 'WOODBURN': ['MID', 'LIV', 4.5], 'MIGNOLET': ['GK', 'LIV', 5.0]}
MCI={'YAYA TOURE': ['MID', 'MCI', 6.5], 'KOLAROV': ['DEF', 'MCI', 5.5], 'IHEANACHO': ['FWD', 'MCI', 7.0],
     'FERNANDO': ['MID', 'MCI', 4.5], 'EDERSON': ['GK', 'MCI', 5.5], 'STERLING': ['MID', 'MCI', 8.0],
     'GUNDOGAN': ['MID', 'MCI', 5.5], 'FERNANDINHO': ['MID', 'MCI', 5.0], 'STONES': ['DEF', 'MCI', 5.5],
     'DELPH': ['MID', 'MCI', 4.5], 'KOMPANY': ['DEF', 'MCI', 6.0], 'SANE': ['MID', 'MCI', 8.5], 'OTAMENDI': ['DEF', 'MCI', 5.5],
     'BRAVO': ['GK', 'MCI', 5.0], 'DE BRUYNE': ['MID', 'MCI', 10.0], 'NOLITO': ['MID', 'MCI', 7.0], 'DAVID SILVA': ['MID', 'MCI', 8.0],
     'AGUERO': ['FWD', 'MCI', 11.5], 'BERNARDO SILVA': ['MID', 'MCI', 8.0], 'JESUS': ['FWD', 'MCI', 10.5]}
MUN={'TUANZEBE': ['DEF', 'MUN', 4.0], 'MKHITARYAN': ['MID', 'MUN', 8.0], 'MARTIAL': ['MID', 'MUN', 8.0], 'DE GEA': ['GK', 'MUN', 5.5], 'HERRERA': ['MID', 'MUN', 5.5], 'LINDELOF': ['DEF', 'MUN', 4.5], 'MCTOMINAY': ['MID', 'MUN', 4.5], 'FOSU-MENSAH': ['DEF', 'MUN', 4.5], 'BAILLY': ['DEF', 'MUN', 6.0], 'JONES': ['DEF', 'MUN', 5.0], 'YOUNG': ['MID', 'MUN', 5.0], 'POGBA': ['MID', 'MUN', 8.0], 'CARRICK': ['MID', 'MUN', 4.5], 'JOEL PEREIRA': ['GK', 'MUN', 4.0], 'VALENCIA': ['DEF', 'MUN', 6.5], 'ROMERO': ['GK', 'MUN', 5.0], 'SMALLING': ['DEF', 'MUN', 5.5], 'DARMIAN': ['DEF', 'MUN', 5.5], 'MATA': ['MID', 'MUN', 7.0], 'SHAW': ['DEF', 'MUN', 5.0], 'ROJO': ['DEF', 'MUN', 5.5], 'FELLAINI': ['MID', 'MUN', 5.0], 'LINGARD': ['MID', 'MUN', 6.0], 'RASHFORD': ['FWD', 'MUN', 7.5], 'LUKAKU': ['FWD', 'MUN', 11.5], 'BLIND': ['DEF', 'MUN', 5.5]}
NEW={'MITROVIC': ['FWD', 'NEW', 5.0], 'RITCHIE': ['MID', 'NEW', 6.0], 'MURPHY': ['FWD', 'NEW', 4.5], 'DARLOW': ['GK', 'NEW', 4.5], 'DUMMETT': ['DEF', 'NEW', 4.5], 'LASCELLES': ['DEF', 'NEW', 4.5], 'SHELVEY': ['MID', 'NEW', 5.5], 'GAMEZ': ['DEF', 'NEW', 4.0], 'GAYLE': ['FWD', 'NEW', 6.5], 'PEREZ': ['FWD', 'NEW', 5.5], 'DIAME': ['MID', 'NEW', 5.0], 'ELLIOT': ['GK', 'NEW', 4.0], 'LEJEUNE': ['DEF', 'NEW', 4.5], 'GOUFFRAN': ['MID', 'NEW', 5.0], 'HANLEY': ['DEF', 'NEW', 4.0], 'COLBACK': ['MID', 'NEW', 4.5], 'YEDLIN': ['DEF', 'NEW', 4.5], 'ATSU': ['MID', 'NEW', 5.0], 'CLARK': ['DEF', 'NEW', 4.5]}
SOU={'GABBIADINI': ['FWD', 'SOU', 7.0], 'YOSHIDA': ['DEF', 'SOU', 5.0], 'WARD-PROWSE': ['MID', 'SOU', 5.5], 'BOUFAL': ['MID', 'SOU', 6.0], 'TARGETT': ['DEF', 'SOU', 4.5], 'BEDNAREK': ['DEF', 'SOU', 4.5], 'HOJBJERG': ['MID', 'SOU', 4.5], 'ALEX MCCARTHY': ['GK', 'SOU', 4.5], 'LONG': ['FWD', 'SOU', 6.0], 'TADIC': ['MID', 'SOU', 6.5], 'VAN DIJK': ['DEF', 'SOU', 5.5], 'SIMS': ['MID', 'SOU', 4.5], 'FORSTER': ['GK', 'SOU', 5.0], 'CEDRIC': ['DEF', 'SOU', 5.0], 'ORIOL ROMEU': ['MID', 'SOU', 4.5], 'AUSTIN': ['FWD', 'SOU', 6.5], 'DAVIS': ['MID', 'SOU', 5.0], 'MCQUEEN': ['DEF', 'SOU', 4.5], 'PIED': ['DEF', 'SOU', 4.5], 'BERTRAND': ['DEF', 'SOU', 5.5], 'REDMOND': ['MID', 'SOU', 6.5], 'STEPHENS': ['DEF', 'SOU', 5.0], 'CLASIE': ['MID', 'SOU', 4.5]}
TOT={'WALKER': ['DEF', 'TOT', 6.5], 'VORM': ['GK', 'TOT', 5.0], 'ERIKSEN': ['MID', 'TOT', 9.5], 'WANYAMA': ['MID', 'TOT', 5.0], 'SISSOKO': ['MID', 'TOT', 5.5], 'LLORIS': ['GK', 'TOT', 5.5], 'DEMBELE': ['MID', 'TOT', 5.0], 'LAMELA': ['MID', 'TOT', 6.5], 'ALLI': ['MID', 'TOT', 9.5], 'BEN DAVIES': ['DEF', 'TOT', 5.5], 'KANE': ['FWD', 'TOT', 12.5], 'DIER': ['MID', 'TOT', 5.0], 'SON': ['MID', 'TOT', 8.0], 'TRIPPIER': ['DEF', 'TOT', 5.5], 'ALDERWEIRELD': ['DEF', 'TOT', 6.0], 'VERTONGHEN': ['DEF', 'TOT', 6.0], 'ROSE': ['DEF', 'TOT', 6.5], 'WINKS': ['MID', 'TOT', 5.0], 'JANSSEN': ['FWD', 'TOT', 7.5], 'WIMMER': ['DEF', 'TOT', 4.5], 'NKOUDOU': ['MID', 'TOT', 5.5]}
STK={'BUTLAND': ['GK', 'STK', 5.0], 'PIETERS': ['DEF', 'STK', 5.0], 'TYMON': ['DEF', 'STK', 4.5], 'BOJAN': ['MID', 'STK', 5.5], 'IMBULA': ['MID', 'STK', 4.5], 'CAMERON': ['DEF', 'STK', 4.5], 'WHELAN': ['MID', 'STK', 4.5], 'SHAWCROSS': ['DEF', 'STK', 5.0], 'MUNIESA': ['DEF', 'STK', 4.5], 'AFELLAY': ['MID', 'STK', 5.0], 'BARDSLEY': ['DEF', 'STK', 4.5], 'BERAHINO': ['FWD', 'STK', 6.0], 'ARNAUTOVIC': ['MID', 'STK', 7.0], 'SHAQIRI': ['MID', 'STK', 6.0], 'ALLEN': ['MID', 'STK', 5.5], 'JOHNSON': ['DEF', 'STK', 4.5], 'CROUCH': ['FWD', 'STK', 5.0], 'DIOUF': ['FWD', 'STK', 5.5], 'GRANT': ['GK', 'STK', 4.5], 'SOBHI': ['MID', 'STK', 5.0], 'ADAM': ['MID', 'STK', 5.0], 'FLETCHER': ['MID', 'STK', 5.0]}
SWA={'FERNANDEZ': ['DEF', 'SWA', 4.5], 'AYEW': ['FWD', 'SWA', 5.0], 'KI SUNG-YUENG': ['MID', 'SWA', 5.0], 'BRITTON': ['MID', 'SWA', 4.5], 'LLORENTE': ['FWD', 'SWA', 7.5], 'RANGEL': ['DEF', 'SWA', 4.0], 'MESA': ['MID', 'SWA', 4.5], 'MCBURNIE': ['FWD', 'SWA', 4.5], 'NAUGHTON': ['DEF', 'SWA', 4.5], 'NARSINGH': ['MID', 'SWA', 5.0], 'BARROW': ['MID', 'SWA', 5.0], 'NORDFELDT': ['GK', 'SWA', 4.0], 'MONTERO': ['MID', 'SWA', 5.0], 'FULTON': ['MID', 'SWA', 4.5], 'FABIANSKI': ['GK', 'SWA', 4.5], 'ROUTLEDGE': ['MID', 'SWA', 5.5], 'MAWSON': ['DEF', 'SWA', 5.0], 'ABRAHAM': ['FWD', 'SWA', 5.5], 'OLSSON': ['DEF', 'SWA', 5.0], 'KINGSLEY': ['DEF', 'SWA', 4.5], 'TOM CARROLL': ['MID', 'SWA', 4.5], 'SIGURDSSON': ['MID', 'SWA', 8.5], 'DYER': ['MID', 'SWA', 4.5], 'VAN DEN HOORN': ['DEF', 'SWA', 4.5], 'FER': ['MID', 'SWA', 5.5]}
WAT={'HUGHES': ['MID', 'WAT', 5.0], 'PRODL': ['DEF', 'WAT', 4.5], 'MARIAPPA': ['DEF', 'WAT', 4.0], 'OKAKA': ['FWD', 'WAT', 5.5], 'MASON': ['DEF', 'WAT', 4.0], 'HOLEBAS': ['DEF', 'WAT', 5.0], 'FEMENIA': ['DEF', 'WAT', 4.5], 'JANMAAT': ['DEF', 'WAT', 5.0], 'AMRABAT': ['MID', 'WAT', 5.0], 'KABASELE': ['DEF', 'WAT', 4.5], 'BERGHUIS': ['MID', 'WAT', 5.0], 'SUCCESS': ['MID', 'WAT', 5.5], 'GOMES': ['GK', 'WAT', 4.5], 'PEREYRA': ['MID', 'WAT', 6.0], 'ZARATE': ['FWD', 'WAT', 5.5], 'KABOUL': ['DEF', 'WAT', 4.5], 'CLEVERLEY': ['MID', 'WAT', 5.0], 'DEENEY': ['FWD', 'WAT', 6.5], 'BEHRAMI': ['MID', 'WAT', 4.5], 'CATHCART': ['DEF', 'WAT', 4.5], 'DOUCOURE': ['MID', 'WAT', 5.0], 'PANTILIMON': ['GK', 'WAT', 4.5], 'BRITOS': ['DEF', 'WAT', 4.5], 'CAPOUE': ['MID', 'WAT', 5.5]}
WBA={'BRUNT': ['MID', 'WBA', 5.5], 'ROBSON-KANU': ['FWD', 'WBA', 5.0], 'MYHILL': ['GK', 'WBA', 4.0], 'RONDON': ['FWD', 'WBA', 6.5], 'CHADLI': ['MID', 'WBA', 6.0], 'LEKO': ['MID', 'WBA', 4.5], 'MCCLEAN': ['MID', 'WBA', 5.0], 'FOSTER': ['GK', 'WBA', 4.5], 'PHILLIPS': ['MID', 'WBA', 6.0], 'DAWSON': ['DEF', 'WBA', 5.0], 'YACOB': ['MID', 'WBA', 4.5], 'LIVERMORE': ['MID', 'WBA', 5.0], 'FIELD': ['MID', 'WBA', 4.5], 'MORRISON': ['MID', 'WBA', 5.5], 'EVANS': ['DEF', 'WBA', 5.0], 'NYOM': ['DEF', 'WBA', 5.0], 'MCAULEY': ['DEF', 'WBA', 5.0], 'RODRIGUEZ': ['FWD', 'WBA', 6.0]}
WHU={'BYRAM': ['DEF', 'WHU', 4.5], 'SNODGRASS': ['MID', 'WHU', 6.0], 'NOBLE': ['MID', 'WHU', 5.5], 'ADRIAN': ['GK', 'WHU', 4.5], 'DIAFRA SAKHO': ['FWD', 'WHU', 5.5], 'FONTE': ['DEF', 'WHU', 5.0], 'KOUYATE': ['MID', 'WHU', 5.0], 'ANTONIO': ['MID', 'WHU', 7.5], 'CARROLL': ['FWD', 'WHU', 6.0], 'LANZINI': ['MID', 'WHU', 7.0], 'ASHLEY FLETCHER': ['FWD', 'WHU', 4.5], 'ZABALETA': ['DEF', 'WHU', 5.0], 'RANDOLPH': ['GK', 'WHU', 4.5], 'ANDRE AYEW': ['MID', 'WHU', 7.0], 'MASUAKU': ['DEF', 'WHU', 4.5], 'REID': ['DEF', 'WHU', 5.0], 'ENNER VALENCIA': ['FWD', 'WHU', 5.0], 'OGBONNA': ['DEF', 'WHU', 4.5], 'FEGHOULI': ['MID', 'WHU', 5.5], 'OBIANG': ['MID', 'WHU', 4.5], 'COLLINS': ['DEF', 'WHU', 4.5], 'FERNANDES': ['MID', 'WHU', 4.5], 'CRESSWELL': ['DEF', 'WHU', 5.0]}

Players=dict(BOU,**BHA,**BUR,**CHE,**CRY,**EVE,**HUD,**LEI,**LIV,**MCI,**MUN,**NEW,**SOU,**TOT,**STK,**SWA,**WAT,**WBA,**WHU)



kraticeKlubov = ["ARS","BOU","BHA","BUR","CHE","CRY","EVE","HUD","LEI","LIV","MUN","NEW","SOU","TOT","STK","SWA","WAT","WBA","WHU"]

#kraticeKlubov= ["MCI"]

POZICIJA = {'Goalkeeper':'GK', 'Defender':'DEF',  'Midfielder': 'MID', 'Forward':'FWD'}

def dobiVelikoCrko(s):
    return [i for i, c in enumerate(s) if c.isupper()]


for kratica in kraticeKlubov:
    with open(kratica+"_team.txt", 'r') as f:
        for vrstica in f:
            vrstica = vrstica.strip()
            vseznam = vrstica.split(" ")
            if len(vseznam) == 6 or len(vseznam) == 7 or 'Bosnia' in vseznam: #ime in priimek
                pozicija = POZICIJA[vseznam[4].split("\t")[1]]
                imePriimek = vseznam[3]
                tr = dobiVelikoCrko(imePriimek)
                ime = imePriimek[tr[1]:]
                priimek = imePriimek[:tr[1]]
                koncnoIme = ime + " " + priimek
            elif len(vseznam) == 4: #eno ime
                nov = vseznam[2].split('\t')
                imePriimek = nov[0]
                tr = dobiVelikoCrko(imePriimek)
                ime = imePriimek[:tr[1]]
                priimek = ime
                pozicija = POZICIJA[nov[1]]
                koncnoIme = ime
            elif len(vseznam) == 8: #več kot dva imena
                nov = vseznam[6].split("\t")
                priimek = nov[0]
                ime = vseznam[2] + " " + vseznam[3]
                pozicija = POZICIJA[nov[1]]
                koncnoIme = ime + " " + priimek
            if "'" in koncnoIme:
                koncnoIme = koncnoIme.replace("'", '"')
            print(koncnoIme, pozicija, kratica)
            #with sqlite3.connect(baza) as con:
                 #cur = con.cursor()  # "odzivnik" za pregledovanje poizvedbe
                 #cur.execute("INSERT INTO  Igralci VALUES (NULL, '{0}', '{1}','{2}',0)".format(koncnoIme, kratica, pozicija))